<h1 style="color:magenta;"><strong>Encoding Categorical data</strong></h1>

Encoding converts categorical/text data into numerical features/format.

In [1]:
import numpy as np
import pandas as pd

np.random.seed(42)

n = 100

df= pd.DataFrame({
    "age":np.random.randint(18,60,n),
    "salary":np.random.randint(30000,100000,n),
    "city":np.random.choice(["Delhi","Mumbai","Pune","Bareilly"],n),
    "gender":np.random.choice(["Male","Female"],n),
    "education":np.random.choice(['High School',"Graduate","Post Graduate"],n)
})

df.head()

   age  salary      city  gender      education
0   56   38392    Mumbai  Female       Graduate
1   46   60535    Mumbai    Male  Post Graduate
2   32   82256      Pune    Male  Post Graduate
3   25   65222      Pune  Female       Graduate
4   38   93335  Bareilly    Male  Post Graduate

<h2>Label Encoder</h2>
Label encode assign unique number to each category

In [3]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['City_label'] = le.fit_transform(df['city'])

<h2>One hot encoder</h2>

Give you sparese matrix(0,1) and generate spearate columns to each category

In [13]:
from sklearn.preprocessing import OneHotEncoder
oe = OneHotEncoder()

encoded= oe.fit_transform(df[['gender']]).toarray()

In [15]:
df[['Female','male']] = encoded

<h2>Ordinal Encode: Used when categories have order</h2>

In [19]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(
    categories=[[
        "High School",
        "Graduate",
        "Post Graduate"
    ]]
)

df['education_encoded'] = oe.fit_transform(df[['education']])

df.head(10)

,age,salary,city,gender,education,City_label,gender_encode,Female,male,education_encoded
0,56,38392,Mumbai,Female,Graduate,2,<Compressed Sparse Row sparse matrix of dtype ...,1.0,0.0,1.0
1,46,60535,Mumbai,Male,Post Graduate,2,<Compressed Sparse Row sparse matrix of dtype ...,0.0,1.0,2.0
2,32,82256,Pune,Male,Post Graduate,3,<Compressed Sparse Row sparse matrix of dtype ...,0.0,1.0,2.0
3,25,65222,Pune,Female,Graduate,3,<Compressed Sparse Row sparse matrix of dtype ...,1.0,0.0,1.0
4,38,93335,Bareilly,Male,Post Graduate,0,<Compressed Sparse Row sparse matrix of dtype ...,0.0,1.0,2.0
5,56,40965,Bareilly,Female,High School,0,<Compressed Sparse Row sparse matrix of dtype ...,1.0,0.0,0.0
6,36,54538,Mumbai,Male,Graduate,2,<Compressed Sparse Row sparse matrix of dtype ...,0.0,1.0,1.0
7,40,38110,Bareilly,Female,Post Graduate,0,<Compressed Sparse Row sparse matrix of dtype ...,1.0,0.0,2.0
8,28,57266,Delhi,Male,Graduate,1,<Compressed Sparse Row sparse matrix of dtype ...,0.0,1.0,1.0
9,28,82992,Bareilly,Female,High School,0,<Compressed Sparse Row sparse matrix of dtype ...,1.0,0.0,0.0