In [2]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

df = pd.read_excel("orders.xlsx")

print(df.head())

  OrderID   OrderDate CustomerID ProductID  Quantity  Discount  TotalAmount  \
0   O0001  2025-08-25       C011      P011         4      0.05      1285.88
1   O0002  2025-12-17       C010      P008         5      0.05      2340.61
2   O0003  2025-01-17       C011      P001         1      0.05        57.08
3   O0004  2025-02-03       C014      P005         7      0.10      1767.15
4   O0005  2025-12-02       C014      P006         6      0.05      1669.53

      Status
0    Shipped
1  Cancelled
2  Cancelled
3    Pending
4    Shipped

In [4]:
orders = pd.read_excel("orders.xlsx",sheet_name="Orders")

In [6]:
orders.head()

,OrderID,OrderDate,CustomerID,ProductID,Quantity,Discount,TotalAmount,Status
0,O0001,2025-08-25,C011,P011,4,0.05,1285.88,Shipped
1,O0002,2025-12-17,C010,P008,5,0.05,2340.61,Cancelled
2,O0003,2025-01-17,C011,P001,1,0.05,57.08,Cancelled
3,O0004,2025-02-03,C014,P005,7,0.10,1767.15,Pending
4,O0005,2025-12-02,C014,P006,6,0.05,1669.53,Shipped

In [7]:
products = pd.read_excel("orders.xlsx",sheet_name="Products")

In [14]:
products.head()

  ProductID ProductName     Category  UnitPrice  Stock
0      P001   Product 1         Home      60.08    117
1      P002   Product 2  Electronics     185.90    108
2      P003   Product 3         Home     405.49    137
3      P004   Product 4  Electronics     486.83    116
4      P005   Product 5  Electronics     280.50    180

In [10]:
customers = pd.read_excel("orders.xlsx",sheet_name="Customers")

In [12]:
customers.head()

  CustomerID CustomerName    City    Segment    JoinDate
0       C001   Customer 1    Pune     Retail  2023-01-26
1       C002   Customer 2    Pune  Corporate  2023-09-08
2       C003   Customer 3  Mumbai     Retail  2025-01-24
3       C004   Customer 4   Delhi        SMB  2025-01-28
4       C005   Customer 5   Noida     Retail  2024-08-27