In [1]:
pip install pandas

Requirement already satisfied: pandas in /opt/homebrew/lib/python3.11/site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in /opt/homebrew/lib/python3.11/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/dhruv/Library/Python/3.11/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/dhruv/Library/Python/3.11/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [44]:
data = {
    'Name':['A','B','C'],
    'Age':[23,25,22]
}

In [45]:
df = pd.DataFrame(data)

In [5]:
type(df)

pandas.DataFrame

In [6]:
df1 = pd.DataFrame([[1,2],[3,4]],columns=['A','B'])
df1

   A  B
0  1  2
1  3  4

In [7]:
df = pd.read_csv('dataset.csv')

In [10]:
df.head(10)

,OrderID,OrderDate,ShipmentDate,CustomerName,Category,Region,Channel,Quantity,UnitPrice,DiscountApplied,SalesAmount
0,1152,2024-07-27,2024-08-04,Customer_327,Electronics,West,Wholesale,15,271.72,True,3668.220
1,500,2024-02-23,2024-03-04,Customer_426,Electronics,North,Online,17,433.52,False,7369.840
2,1337,2022-04-27,2022-05-06,Customer_379,Electronics,East,Retail,6,434.97,False,2609.820
3,1033,2022-02-24,2022-03-02,Customer_381,Food,West,Wholesale,12,283.51,True,3061.908
4,281,2023-11-16,2023-11-19,Customer_208,Furniture,South,Retail,15,49.16,True,663.660
5,1659,2022-05-26,2022-06-01,Customer_237,Clothing,South,Wholesale,6,167.90,False,1007.400
6,1329,2022-07-25,2022-07-28,Customer_98,Food,West,Retail,13,255.81,False,3325.530
7,211,2024-04-01,2024-04-02,Customer_271,Clothing,South,Retail,19,111.47,False,2117.930
8,1261,2022-07-11,2022-07-14,Customer_359,Electronics,East,Wholesale,6,295.84,False,1775.040
9,1910,2024-07-28,2024-08-03,Customer_233,Electronics,North,Online,17,156.16,True,2389.248

In [12]:
df.tail(10)

,OrderID,OrderDate,ShipmentDate,CustomerName,Category,Region,Channel,Quantity,UnitPrice,DiscountApplied,SalesAmount
1990,1694,2023-10-10,2023-10-11,Customer_258,Electronics,North,Wholesale,18,470.86,True,7627.932
1991,371,2024-06-14,2024-06-17,Customer_269,Clothing,West,Retail,7,33.79,False,236.530
1992,1304,2024-05-18,2024-05-23,Customer_149,Furniture,South,Wholesale,11,299.98,True,2969.802
1993,1450,2024-06-29,2024-07-07,Customer_137,Electronics,North,Online,11,430.08,True,4257.792
1994,435,2024-06-09,2024-06-16,Customer_407,Furniture,North,Retail,8,469.60,False,3756.800
1995,894,2022-06-05,2022-06-08,Customer_247,Furniture,South,Wholesale,6,248.45,False,1490.700
1996,1837,2024-03-30,2024-04-08,Customer_427,Food,North,Wholesale,16,194.62,True,2802.528
1997,1702,2023-06-01,2023-06-07,Customer_135,Furniture,East,Online,6,118.02,False,708.120
1998,957,2024-02-14,2024-02-19,Customer_64,Furniture,West,Online,6,487.15,True,2630.610
1999,939,2024-12-13,2024-12-22,Customer_25,Electronics,North,Wholesale,14,136.99,False,1917.860

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          2000 non-null   int64
 1   OrderDate        2000 non-null   str
 2   ShipmentDate     2000 non-null   str
 3   CustomerName     2000 non-null   str
 4   Category         2000 non-null   str
 5   Region           2000 non-null   str
 6   Channel          2000 non-null   str
 7   Quantity         2000 non-null   int64
 8   UnitPrice        2000 non-null   float64
 9   DiscountApplied  2000 non-null   bool
 10  SalesAmount      2000 non-null   float64
dtypes: bool(1), float64(2), int64(2), str(6)
memory usage: 158.3 KB

In [14]:
df.describe()

           OrderID     Quantity    UnitPrice  SalesAmount
count  2000.000000  2000.000000  2000.000000  2000.000000
mean   1000.500000    10.195500   253.750990  2458.940332
std     577.494589     5.419868   141.864924  2024.978250
min       1.000000     1.000000     5.120000     6.550000
25%     500.750000     5.750000   130.815000   812.524500
50%    1000.500000    10.000000   253.375000  1901.762500
75%    1500.250000    15.000000   376.955000  3679.098000
max    2000.000000    19.000000   499.840000  9059.010000

In [17]:
df.shape

(2000, 11)

In [20]:
sr = pd.Series([23,123,34,3,54])

In [21]:
sr

0     23
1    123
2     34
3      3
4     54
dtype: int64

In [24]:
df[['CustomerName','SalesAmount']].head()

   CustomerName  SalesAmount
0  Customer_327     3668.220
1  Customer_426     7369.840
2  Customer_379     2609.820
3  Customer_381     3061.908
4  Customer_208      663.660

In [27]:
df.loc[0:10,'CustomerName']

0     Customer_327
1     Customer_426
2     Customer_379
3     Customer_381
4     Customer_208
5     Customer_237
6      Customer_98
7     Customer_271
8     Customer_359
9     Customer_233
10    Customer_247
Name: CustomerName, dtype: str

In [30]:
df.iloc[0:10,0:5]

   OrderID   OrderDate ShipmentDate  CustomerName     Category
0     1152  2024-07-27   2024-08-04  Customer_327  Electronics
1      500  2024-02-23   2024-03-04  Customer_426  Electronics
2     1337  2022-04-27   2022-05-06  Customer_379  Electronics
3     1033  2022-02-24   2022-03-02  Customer_381         Food
4      281  2023-11-16   2023-11-19  Customer_208    Furniture
5     1659  2022-05-26   2022-06-01  Customer_237     Clothing
6     1329  2022-07-25   2022-07-28   Customer_98         Food
7      211  2024-04-01   2024-04-02  Customer_271     Clothing
8     1261  2022-07-11   2022-07-14  Customer_359  Electronics
9     1910  2024-07-28   2024-08-03  Customer_233  Electronics

In [31]:
df[df['Quantity']>15]

,OrderID,OrderDate,ShipmentDate,CustomerName,Category,Region,Channel,Quantity,UnitPrice,DiscountApplied,SalesAmount
1,500,2024-02-23,2024-03-04,Customer_426,Electronics,North,Online,17,433.52,False,7369.840
7,211,2024-04-01,2024-04-02,Customer_271,Clothing,South,Retail,19,111.47,False,2117.930
9,1910,2024-07-28,2024-08-03,Customer_233,Electronics,North,Online,17,156.16,True,2389.248
10,189,2022-01-02,2022-01-09,Customer_247,Electronics,West,Wholesale,19,216.32,False,4110.080
15,241,2024-12-08,2024-12-09,Customer_295,Furniture,North,Wholesale,18,397.27,True,6435.774
...,...,...,...,...,...,...,...,...,...,...,...
1979,336,2023-12-05,2023-12-09,Customer_58,Electronics,East,Online,16,495.84,False,7933.440
1982,78,2023-10-10,2023-10-17,Customer_212,Clothing,East,Wholesale,16,71.30,False,1140.800
1986,181,2023-04-18,2023-04-22,Customer_355,Furniture,East,Online,17,146.33,False,2487.610
1990,1694,2023-10-10,2023-10-11,Customer_258,Electronics,North,Wholesale,18,470.86,True,7627.932
1996,1837,2024-03-30,2024-04-08,Customer_427,Food,North,Wholesale,16,194.62,True,2802.528

In [37]:
temp = df[(df['Region']=="North")&(df['DiscountApplied']==True)][['OrderID','OrderDate','Category','Channel','Quantity','SalesAmount']]

In [39]:
temp.to_csv("SpecificRecords.csv")

In [42]:
pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [43]:
temp.to_excel("SpecificRecords.xlsx")