<h2>Combining Data</h2>

In [1]:
import pandas as pd

In [2]:
sales = pd.read_csv('data/fact_sales.csv')
customers = pd.read_csv('data/customers.csv')
products = pd.read_csv('data/products.csv')

In [3]:
sales.head()

,order_number,product_key,customer_key,order_date,shipping_date,due_date,sales_amount,quantity,price
0,SO54496,282,5400,2013-03-16,2013-03-23,2013-03-28,25,1,25
1,SO54496,289,5400,2013-03-16,2013-03-23,2013-03-28,5,1,5
2,SO54496,259,5400,2013-03-16,2013-03-23,2013-03-28,2,1,2
3,SO54497,174,9281,2013-03-16,2013-03-23,2013-03-28,22,1,22
4,SO54497,280,9281,2013-03-16,2013-03-23,2013-03-28,9,1,9

In [4]:
customers.head()

,customer_key,customer_id,customer_number,first_name,last_name,country,marital_status,gender,birthdate,create_date
0,1,11000,AW00011000,Jon,Yang,Australia,Married,Male,1971-10-06,2025-10-06
1,2,11001,AW00011001,Eugene,Huang,Australia,Single,Male,1976-05-10,2025-10-06
2,3,11002,AW00011002,Ruben,Torres,Australia,Married,Male,1971-02-09,2025-10-06
3,4,11003,AW00011003,Christy,Zhu,Australia,Single,Female,1973-08-14,2025-10-06
4,5,11004,AW00011004,Elizabeth,Johnson,Australia,Single,Female,1979-08-05,2025-10-06

In [5]:
products.head()

,product_key,product_id,product_number,product_name,category_id,category,subcategory,maintenance,cost,product_line,start_date
0,1,210,FR-R92B-58,HL Road Frame - Black- 58,CO_RF,Components,Road Frames,Yes,0,Road,2003-07-01
1,2,211,FR-R92R-58,HL Road Frame - Red- 58,CO_RF,Components,Road Frames,Yes,0,Road,2003-07-01
2,3,348,BK-M82B-38,Mountain-100 Black- 38,BI_MB,Bikes,Mountain Bikes,Yes,1898,Mountain,2011-07-01
3,4,349,BK-M82B-42,Mountain-100 Black- 42,BI_MB,Bikes,Mountain Bikes,Yes,1898,Mountain,2011-07-01
4,5,350,BK-M82B-44,Mountain-100 Black- 44,BI_MB,Bikes,Mountain Bikes,Yes,1898,Mountain,2011-07-01

In [7]:
sales.shape

(60398, 9)

In [24]:
products.shape

(295, 11)

In [25]:
customers.shape

(18484, 10)

In [8]:
chunk1 = sales.iloc[0:30000,0:]

In [9]:
chunk1.shape

(30000, 9)

In [10]:
chunk2 = sales.iloc[30000:60398,0:]

In [11]:
chunk2.shape

(30398, 9)

In [12]:
chunk1.head()

,order_number,product_key,customer_key,order_date,shipping_date,due_date,sales_amount,quantity,price
0,SO54496,282,5400,2013-03-16,2013-03-23,2013-03-28,25,1,25
1,SO54496,289,5400,2013-03-16,2013-03-23,2013-03-28,5,1,5
2,SO54496,259,5400,2013-03-16,2013-03-23,2013-03-28,2,1,2
3,SO54497,174,9281,2013-03-16,2013-03-23,2013-03-28,22,1,22
4,SO54497,280,9281,2013-03-16,2013-03-23,2013-03-28,9,1,9

In [13]:
chunk2.head()

,order_number,product_key,customer_key,order_date,shipping_date,due_date,sales_amount,quantity,price
30000,SO67633,244,16251,2013-10-02,2013-10-09,2013-10-14,35,1,35
30001,SO67634,155,12795,2013-10-02,2013-10-09,2013-10-14,1215,1,1215
30002,SO67634,244,12795,2013-10-02,2013-10-09,2013-10-14,35,1,35
30003,SO67635,132,10397,2013-10-02,2013-10-09,2013-10-14,1120,1,1120
30004,SO67635,248,10397,2013-10-02,2013-10-09,2013-10-14,50,1,50

In [14]:
df = pd.concat([chunk1,chunk2])

In [16]:
df.shape

(60398, 9)

In [28]:
temp = pd.merge(pd.merge(sales,customers,on='customer_key'),products,on='product_key')

In [30]:
df = temp[['order_number',
           'order_date',
           'shipping_date',
           'sales_amount',
           'quantity',
           'product_number',
           'product_name',
           'category',
           'maintenance',
           'cost',
           'product_line',
           'start_date',
           'customer_number',
           'first_name',
           'last_name',
           "country",
           'marital_status',
           'gender',
           'create_date']]

In [32]:
df.head()

,order_number,order_date,shipping_date,sales_amount,quantity,product_number,product_name,category,maintenance,cost,product_line,start_date,customer_number,first_name,last_name,country,marital_status,gender,create_date
0,SO54496,2013-03-16,2013-03-23,25,1,TI-M267,LL Mountain Tire,Accessories,Yes,9,Mountain,2013-07-01,AW00016399,Arturo,Xu,Germany,Single,Male,2026-01-04
1,SO54496,2013-03-16,2013-03-23,5,1,TT-M928,Mountain Tire Tube,Accessories,Yes,2,Mountain,2013-07-01,AW00016399,Arturo,Xu,Germany,Single,Male,2026-01-04
2,SO54496,2013-03-16,2013-03-23,2,1,PK-7098,Patch Kit/8 Patches,Accessories,Yes,1,Other Sales,2013-07-01,AW00016399,Arturo,Xu,Germany,Single,Male,2026-01-04
3,SO54497,2013-03-16,2013-03-23,22,1,FE-6654,Fender Set - Mountain,Accessories,No,8,Mountain,2013-07-01,AW00020280,Joshua,Harris,Canada,Single,Male,2026-01-05
4,SO54497,2013-03-16,2013-03-23,9,1,SO-R809-M,Racing Socks- M,Clothing,No,3,Road,2013-07-01,AW00020280,Joshua,Harris,Canada,Single,Male,2026-01-05

In [33]:
df.dtypes

order_number         str
order_date           str
shipping_date        str
sales_amount       int64
quantity           int64
product_number       str
product_name         str
category             str
maintenance          str
cost               int64
product_line         str
start_date           str
customer_number      str
first_name           str
last_name            str
country              str
marital_status       str
gender               str
create_date          str
dtype: object

In [34]:
df['shipping_date'] = pd.to_datetime(df['shipping_date'])
df['order_date'] = pd.to_datetime(df['order_date'])
df['start_date'] = pd.to_datetime(df['start_date'])
df['create_date'] = pd.to_datetime(df['create_date'])

In [35]:
df.dtypes

order_number                  str
order_date         datetime64[us]
shipping_date      datetime64[us]
sales_amount                int64
quantity                    int64
product_number                str
product_name                  str
category                      str
maintenance                   str
cost                        int64
product_line                  str
start_date         datetime64[us]
customer_number               str
first_name                    str
last_name                     str
country                       str
marital_status                str
gender                        str
create_date        datetime64[us]
dtype: object

In [39]:
df['Month'] = df['order_date'].dt.month

In [40]:
df.shape

(60398, 20)

In [41]:
df.head()

,order_number,order_date,shipping_date,sales_amount,quantity,product_number,product_name,category,maintenance,cost,product_line,start_date,customer_number,first_name,last_name,country,marital_status,gender,create_date,Month
0,SO54496,2013-03-16,2013-03-23,25,1,TI-M267,LL Mountain Tire,Accessories,Yes,9,Mountain,2013-07-01,AW00016399,Arturo,Xu,Germany,Single,Male,2026-01-04,3.0
1,SO54496,2013-03-16,2013-03-23,5,1,TT-M928,Mountain Tire Tube,Accessories,Yes,2,Mountain,2013-07-01,AW00016399,Arturo,Xu,Germany,Single,Male,2026-01-04,3.0
2,SO54496,2013-03-16,2013-03-23,2,1,PK-7098,Patch Kit/8 Patches,Accessories,Yes,1,Other Sales,2013-07-01,AW00016399,Arturo,Xu,Germany,Single,Male,2026-01-04,3.0
3,SO54497,2013-03-16,2013-03-23,22,1,FE-6654,Fender Set - Mountain,Accessories,No,8,Mountain,2013-07-01,AW00020280,Joshua,Harris,Canada,Single,Male,2026-01-05,3.0
4,SO54497,2013-03-16,2013-03-23,9,1,SO-R809-M,Racing Socks- M,Clothing,No,3,Road,2013-07-01,AW00020280,Joshua,Harris,Canada,Single,Male,2026-01-05,3.0

In [42]:
df.tail()

,order_number,order_date,shipping_date,sales_amount,quantity,product_number,product_name,category,maintenance,cost,product_line,start_date,customer_number,first_name,last_name,country,marital_status,gender,create_date,Month
60393,SO54494,2013-03-16,2013-03-23,2,1,PK-7098,Patch Kit/8 Patches,Accessories,Yes,1,Other Sales,2013-07-01,AW00022278,Mariah,Gray,Canada,Single,Female,2026-01-05,3.0
60394,SO54495,2013-03-16,2013-03-23,5,1,TT-M928,Mountain Tire Tube,Accessories,Yes,2,Mountain,2013-07-01,AW00014749,Jose,Jenkins,United States,Married,Male,2025-10-12,3.0
60395,SO54495,2013-03-16,2013-03-23,35,1,HL-U509,Sport-100 Helmet- Black,Accessories,Yes,13,Other Sales,2013-07-01,AW00014749,Jose,Jenkins,United States,Married,Male,2025-10-12,3.0
60396,SO54495,2013-03-16,2013-03-23,50,1,LJ-0192-L,Long-Sleeve Logo Jersey- L,Clothing,No,38,Other Sales,2013-07-01,AW00014749,Jose,Jenkins,United States,Married,Male,2025-10-12,3.0
60397,SO54495,2013-03-16,2013-03-23,9,1,CA-1098,AWC Logo Cap,Clothing,No,7,Other Sales,2013-07-01,AW00014749,Jose,Jenkins,United States,Married,Male,2025-10-12,3.0

In [51]:
df.sort_values('Month')

,order_number,order_date,shipping_date,sales_amount,quantity,product_number,product_name,category,maintenance,cost,product_line,start_date,customer_number,first_name,last_name,country,marital_status,gender,create_date,Month
50063,SO46897,2012-01-24,2012-01-31,2443,1,BK-R89R-44,Road-250 Red- 44,Bikes,Yes,1519,Road,2012-07-01,AW00021179,Jaclyn,Zhou,Australia,Married,Female,2026-01-05,1.0
47756,SO43817,2011-01-24,2011-01-31,3578,1,BK-R93R-62,Road-150 Red- 62,Bikes,Yes,2171,Road,2011-07-01,AW00016519,Yolanda,Chander,Australia,Single,Female,2026-01-04,1.0
47755,SO43816,2011-01-24,2011-01-31,3578,1,BK-R93R-56,Road-150 Red- 56,Bikes,Yes,2171,Road,2011-07-01,AW00016496,Dawn,Tang,Australia,Single,Female,2026-01-04,1.0
47754,SO43815,2011-01-24,2011-01-31,3578,1,BK-R93R-44,Road-150 Red- 44,Bikes,Yes,2171,Road,2011-07-01,AW00016494,Jordyn,Simmons,Australia,Single,Female,2026-01-04,1.0
47753,SO43814,2011-01-24,2011-01-31,3375,1,BK-M82B-44,Mountain-100 Black- 44,Bikes,Yes,1898,Mountain,2011-07-01,AW00025866,Tristan,Perry,United States,Married,Male,2026-01-14,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41488,SO72588,2013-12-08,2013-12-15,2295,1,BK-M68B-42,Mountain-200 Black- 42,Bikes,Yes,1252,Mountain,2013-07-01,AW00022836,Michele,Sai,Germany,Single,Female,2026-01-05,12.0
41487,SO72587,2013-12-08,2013-12-15,8,1,CL-9009,Bike Wash - Dissolver,Accessories,Yes,3,Other Sales,2013-07-01,AW00020931,Brian,Sanchez,United Kingdom,Married,Male,2026-01-05,12.0
41486,SO72587,2013-12-08,2013-12-15,2,1,PK-7098,Patch Kit/8 Patches,Accessories,Yes,1,Other Sales,2013-07-01,AW00020931,Brian,Sanchez,United Kingdom,Married,Male,2026-01-05,12.0
41495,SO72590,2013-12-08,2013-12-15,54,1,SJ-0194-M,Short-Sleeve Classic Jersey- M,Clothing,No,42,Other Sales,2013-07-01,AW00019454,Roger,Sharma,Germany,Married,Male,2026-01-05,12.0
43180,SO73257,2013-12-17,2013-12-24,120,1,RA-H123,Hitch Rack - 4-Bike,Accessories,Yes,45,Other Sales,2013-07-01,AW00011711,Daniel,Davis,Canada,Single,Male,2025-10-08,12.0

In [46]:
df.isnull().sum()/len(df) * 100

order_number       0.000000
order_date         0.031458
shipping_date      0.000000
sales_amount       0.000000
quantity           0.000000
product_number     0.000000
product_name       0.000000
category           0.000000
maintenance        0.000000
cost               0.000000
product_line       0.000000
start_date         0.000000
customer_number    0.000000
first_name         0.000000
last_name          0.000000
country            1.442101
marital_status     0.000000
gender             0.054638
create_date        0.000000
Month              0.031458
dtype: float64

In [48]:
df.dropna(inplace=True)

In [49]:
df.isnull().sum()

order_number       0
order_date         0
shipping_date      0
sales_amount       0
quantity           0
product_number     0
product_name       0
category           0
maintenance        0
cost               0
product_line       0
start_date         0
customer_number    0
first_name         0
last_name          0
country            0
marital_status     0
gender             0
create_date        0
Month              0
dtype: int64

In [50]:
df.shape

(59475, 20)