In [1]:
import pandas as pd

df = pd.read_csv('dataset.csv')

In [2]:
df.head()

,OrderID,OrderDate,ShipmentDate,CustomerName,Category,Region,Channel,Quantity,UnitPrice,DiscountApplied,SalesAmount
0,1152,2024-07-27,2024-08-04,Customer_327,Electronics,West,Wholesale,15,271.72,True,3668.220
1,500,2024-02-23,2024-03-04,Customer_426,Electronics,North,Online,17,433.52,False,7369.840
2,1337,2022-04-27,2022-05-06,Customer_379,Electronics,East,Retail,6,434.97,False,2609.820
3,1033,2022-02-24,2022-03-02,Customer_381,Food,West,Wholesale,12,283.51,True,3061.908
4,281,2023-11-16,2023-11-19,Customer_208,Furniture,South,Retail,15,49.16,True,663.660

In [3]:
df.groupby('Category')['SalesAmount'].sum()

Category
Clothing       1284500.648
Electronics    1317491.969
Food           1120211.564
Furniture      1195676.483
Name: SalesAmount, dtype: float64

In [4]:
df.groupby(['Category','Channel'])['SalesAmount'].sum()

Category     Channel
Clothing     Online       488179.532
             Retail       410826.261
             Wholesale    385494.855
Electronics  Online       522072.729
             Retail       382439.822
             Wholesale    412979.418
Food         Online       417919.216
             Retail       319909.354
             Wholesale    382382.994
Furniture    Online       407141.930
             Retail       396308.063
             Wholesale    392226.490
Name: SalesAmount, dtype: float64

In [5]:
df.groupby(['Category','Channel'])[['SalesAmount','Quantity']].sum()

                       SalesAmount  Quantity
Category    Channel
Clothing    Online      488179.532      1988
            Retail      410826.261      1831
            Wholesale   385494.855      1570
Electronics Online      522072.729      1996
            Retail      382439.822      1636
            Wholesale   412979.418      1667
Food        Online      417919.216      1903
            Retail      319909.354      1453
            Wholesale   382382.994      1463
Furniture   Online      407141.930      1770
            Retail      396308.063      1606
            Wholesale   392226.490      1508

In [6]:
df.groupby(['Category','Channel'])[['SalesAmount','Quantity']].agg(['sum','mean','min','max'])

                      SalesAmount                                Quantity  \
                              sum         mean     min       max      sum
Category    Channel
Clothing    Online     488179.532  2638.808281   6.550  8244.180     1988
            Retail     410826.261  2321.052322  51.084  9059.010     1831
            Wholesale  385494.855  2379.597870  11.169  8082.540     1570
Electronics Online     522072.729  2932.992860  49.710  8586.860     1996
            Retail     382439.822  2390.248887  14.980  8457.480     1636
            Wholesale  412979.418  2415.084316  45.030  7627.932     1667
Food        Online     417919.216  2211.212783  36.729  8015.530     1903
            Retail     319909.354  2118.604993  20.870  8246.880     1453
            Wholesale  382382.994  2583.668878   7.830  7333.578     1463
Furniture   Online     407141.930  2326.525314  25.600  8029.134     1770
            Retail     396308.063  2590.248778  25.320  8908.530     1606
            Wholesale  392226.490  2597.526424  23.661  8957.740     1508


                            mean min max
Category    Channel
Clothing    Online     10.745946   1  19
            Retail     10.344633   1  19
            Wholesale   9.691358   1  19
Electronics Online     11.213483   1  19
            Retail     10.225000   1  19
            Wholesale   9.748538   1  19
Food        Online     10.068783   1  19
            Retail      9.622517   1  19
            Wholesale   9.885135   1  19
Furniture   Online     10.114286   1  19
            Retail     10.496732   1  19
            Wholesale   9.986755   1  19

In [7]:
df.pivot_table(values='SalesAmount',index='Category',columns=['Region','Channel'],aggfunc=["max",'min'])

                  max                                                   \
Region           East                         North
Channel        Online    Retail Wholesale    Online   Retail Wholesale
Category
Clothing     7489.458  6956.880   6524.01  8081.080  6316.05  8082.540
Electronics  7938.010  7528.110   5583.63  7723.188  6767.84  7627.932
Food         7137.900  7911.790   7174.72  7612.160  6654.15  7333.578
Furniture    7112.817  8265.627   8957.74  6816.609  6993.76  8320.176

                                                    ...       min          \
Region          South                         West  ...      East   North
Channel        Online    Retail Wholesale   Online  ... Wholesale  Online
Category                                            ...
Clothing     8244.180  6733.584  6391.170  7745.44  ...    17.690  48.820
Electronics  8200.020  6585.630  6480.927  8586.86  ...    63.927  95.589
Food         8011.179  8246.880  7316.406  8015.53  ...   113.553  49.060
Furniture    8029.134  8908.530  7631.200  7888.80  ...   155.763  90.900

                                                                          \
Region                           South                     West
Channel      Retail Wholesale   Online Retail Wholesale  Online   Retail
Category
Clothing     51.084    53.991   92.990  58.64    53.865   65.19  162.324
Electronics  66.680    87.993  142.578  56.89   106.965  311.58   14.980
Food         52.677    76.360   99.880  56.12     7.830  224.74   20.870
Furniture    43.983    63.960   38.682  87.76    23.661   39.69   25.320


Region
Channel     Wholesale
Category
Clothing       11.169
Electronics    45.030
Food           61.750
Furniture     141.300

[4 rows x 24 columns]

In [8]:
df['OrderDate'] = pd.to_datetime(df['OrderDate'])

In [17]:
df.dtypes

OrderID                     int64
OrderDate          datetime64[us]
ShipmentDate                  str
CustomerName                  str
Category                      str
Region                        str
Channel                       str
Quantity                    int64
UnitPrice                 float64
DiscountApplied              bool
SalesAmount               float64
dtype: object

In [9]:
df['Month'] = df['OrderDate'].dt.month

In [10]:
df['Year'] = df['OrderDate'].dt.year

In [11]:
df

,OrderID,OrderDate,ShipmentDate,CustomerName,Category,Region,Channel,Quantity,UnitPrice,DiscountApplied,SalesAmount,Month,Year
0,1152,2024-07-27,2024-08-04,Customer_327,Electronics,West,Wholesale,15,271.72,True,3668.220,7,2024
1,500,2024-02-23,2024-03-04,Customer_426,Electronics,North,Online,17,433.52,False,7369.840,2,2024
2,1337,2022-04-27,2022-05-06,Customer_379,Electronics,East,Retail,6,434.97,False,2609.820,4,2022
3,1033,2022-02-24,2022-03-02,Customer_381,Food,West,Wholesale,12,283.51,True,3061.908,2,2022
4,281,2023-11-16,2023-11-19,Customer_208,Furniture,South,Retail,15,49.16,True,663.660,11,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,894,2022-06-05,2022-06-08,Customer_247,Furniture,South,Wholesale,6,248.45,False,1490.700,6,2022
1996,1837,2024-03-30,2024-04-08,Customer_427,Food,North,Wholesale,16,194.62,True,2802.528,3,2024
1997,1702,2023-06-01,2023-06-07,Customer_135,Furniture,East,Online,6,118.02,False,708.120,6,2023
1998,957,2024-02-14,2024-02-19,Customer_64,Furniture,West,Online,6,487.15,True,2630.610,2,2024
1999,939,2024-12-13,2024-12-22,Customer_25,Electronics,North,Wholesale,14,136.99,False,1917.860,12,2024

In [12]:
df.groupby('Month')['SalesAmount'].sum()

Month
1     453905.519
2     396955.530
3     400772.983
4     432722.772
5     446728.349
6     331446.459
7     381639.783
8     374819.086
9     342857.713
10    442697.002
11    399410.655
12    513924.813
Name: SalesAmount, dtype: float64

In [13]:
df.pivot_table(index=['Year','Month'],values='SalesAmount',columns='Region',aggfunc='sum')

Region           East      North      South       West
Year Month
2022 1      23971.670  74492.099  31183.699  60846.832
     2      22518.739  33436.634  29033.585  37365.439
     3      18148.220  25002.176  24567.725  35406.386
     4      40838.120  29917.332  37754.291  17934.764
     5      56189.285  26106.711  44094.854  46502.429
     6      12066.908  20127.901  26760.244  46997.179
     7      42322.381  20759.910  14859.805  50324.614
     8      16543.371  23490.295  20450.466  48726.520
     9      14514.010  51458.714  14859.576  22010.206
     10     14240.701  15942.316  40793.206  32422.320
     11     46324.604  37321.927  21970.922  26198.008
     12     55602.623  29421.291  68126.695  48783.820
2023 1      44474.198  27912.553  35740.669  40484.586
     2      16436.853  47289.814  34778.069  34618.988
     3      37543.606  46437.207  40279.570  18688.144
     4      23715.577  39764.915  60218.994  17970.403
     5      29876.920  35951.356  32980.074  40381.742
     6      22344.655  30406.367  30806.069  15123.908
     7      41888.248  15723.126  28465.245  31830.817
     8      35441.930  35524.634  24254.417  19406.967
     9      24062.951  18388.400  41230.116  24440.281
     10     45267.824  48818.794  29234.396  32525.659
     11     41655.342  24691.305  36780.457  39288.498
     12     65713.058  50708.183  39972.707  42775.381
2024 1      31808.647  26442.584  27460.071  29087.911
     2      43479.051  25629.112  45944.630  26424.616
     3      10530.107  34519.728  63276.094  46374.020
     4      56764.258  43985.524  36498.065  27360.529
     5      37827.422  37085.327  32061.287  27670.942
     6      26236.250  34869.665  42440.282  23267.031
     7      32751.283  42695.421  32398.888  27620.045
     8      37033.472  27261.694  38242.209  48443.111
     9      23766.952  37913.772  33332.029  36880.706
     10     44287.631  30970.308  62105.696  46088.151
     11     40463.395  19921.389  41702.532  23092.276
     12     27030.431  44920.179  25385.212  15485.233

In [14]:
print(df['SalesAmount'].sum())

4917880.664

In [30]:
len(df[df['DiscountApplied']==True])

1009

In [31]:
len(df[df['DiscountApplied']==False])

991

In [15]:
len(df[df['DiscountApplied']==True])/len(df) * 100

50.449999999999996

In [22]:
print(df[df['Channel']=='Online']['SalesAmount'].sum()/df['SalesAmount'].sum()*100)

37.319193620026404