Transforming features so they are on similar scale.

<h1><strong>Standard Scaler</strong></h1>

In [10]:
import pandas as pd
import numpy as np

data = {
    'age':np.random.randint(20,55,100),
    'salary':np.random.randint(30000,100000,100)
}
df = pd.DataFrame(data)

In [ ]:
df.head()

In [ ]:
pip install scikit-learn

In [12]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

df[["age_scaled","salary_scaled"]] = scaler.fit_transform(df[['age','salary']])

In [13]:
df.head()

   age  salary  age_scaled  salary_scaled
0   32   73688   -0.772591       0.501003
1   27   62422   -1.326817      -0.065301
2   33   61521   -0.661746      -0.110592
3   35   61619   -0.440055      -0.105666
4   43   71805    0.446706       0.406351

<code>Z-score Formula:</code>

$$Z =\frac{X - \mu}{\sigma} $$

In [14]:
df['age_scaled_manual'] = (df['age'] - df['age'].mean())/df['age'].std()

In [16]:
df['age_inverse_manual'] = df['age_scaled_manual']*df['age'].std() + df['age'].mean()

In [17]:
df.head()

,age,salary,age_scaled,salary_scaled,age_scaled_manual,age_inverse_manual
0,32,73688,-0.772591,0.501003,-0.768718,32.0
1,27,62422,-1.326817,-0.065301,-1.320166,27.0
2,33,61521,-0.661746,-0.110592,-0.658429,33.0
3,35,61619,-0.440055,-0.105666,-0.437850,35.0
4,43,71805,0.446706,0.406351,0.444467,43.0

In [18]:
df[['age_inverse','salary_inverse']] = scaler.inverse_transform(df[['age_scaled','salary_scaled']])

In [19]:
df.head()

,age,salary,age_scaled,salary_scaled,age_scaled_manual,age_inverse_manual,age_inverse,salary_inverse
0,32,73688,-0.772591,0.501003,-0.768718,32.0,32.0,73688.0
1,27,62422,-1.326817,-0.065301,-1.320166,27.0,27.0,62422.0
2,33,61521,-0.661746,-0.110592,-0.658429,33.0,33.0,61521.0
3,35,61619,-0.440055,-0.105666,-0.437850,35.0,35.0,61619.0
4,43,71805,0.446706,0.406351,0.444467,43.0,43.0,71805.0

<h1><strong>Min-Max Scaler</strong></h1>

<code>Min-Max Scaler Formula: </code>
$$X_{scaled} = \frac{X - X_{min}}{X_{max}-X_{min}}$$

In [43]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df[['age_mimx','salary_mimx']] = scaler.fit_transform(df[['age','salary']])

In [44]:
df.head()

,age,salary,age_scaled,salary_scaled,age_scaled_manual,age_inverse_manual,age_inverse,salary_inverse,age_mimx,salary_mimx,salary_mimx_manual,age_inverse_mimx,salary_inverse_mimx
0,32,73688,-0.772591,0.501003,-0.768718,32.0,32.0,73688.0,0.333333,0.624958,0.624958,73688.0,73688.0
1,27,62422,-1.326817,-0.065301,-1.320166,27.0,27.0,62422.0,0.181818,0.461501,0.461501,62422.0,62422.0
2,33,61521,-0.661746,-0.110592,-0.658429,33.0,33.0,61521.0,0.363636,0.448428,0.448428,61521.0,61521.0
3,35,61619,-0.440055,-0.105666,-0.437850,35.0,35.0,61619.0,0.424242,0.449850,0.449850,61619.0,61619.0
4,43,71805,0.446706,0.406351,0.444467,43.0,43.0,71805.0,0.666667,0.597638,0.597638,71805.0,71805.0

In [22]:
minn = df['salary'].min()
maxx = df['salary'].max()

In [23]:
df['salary_mimx_manual'] =( df['salary'] - minn )/(maxx - minn)

In [24]:
df.head()

,age,salary,age_scaled,salary_scaled,age_scaled_manual,age_inverse_manual,age_inverse,salary_inverse,age_mimx,salary_mimx,salary_mimx_manual
0,32,73688,-0.772591,0.501003,-0.768718,32.0,32.0,73688.0,0.333333,0.624958,0.624958
1,27,62422,-1.326817,-0.065301,-1.320166,27.0,27.0,62422.0,0.181818,0.461501,0.461501
2,33,61521,-0.661746,-0.110592,-0.658429,33.0,33.0,61521.0,0.363636,0.448428,0.448428
3,35,61619,-0.440055,-0.105666,-0.437850,35.0,35.0,61619.0,0.424242,0.449850,0.449850
4,43,71805,0.446706,0.406351,0.444467,43.0,43.0,71805.0,0.666667,0.597638,0.597638

In [32]:
df['salary_inverse_mimx'] = df['salary_mimx_manual'] * (maxx-minn) + minn

In [31]:
df.head()

,age,salary,age_scaled,salary_scaled,age_scaled_manual,age_inverse_manual,age_inverse,salary_inverse,age_mimx,salary_mimx,salary_mimx_manual,age_inverse_mimx,salary_inverse_mimx
0,32,73688,-0.772591,0.501003,-0.768718,32.0,32.0,73688.0,0.333333,0.624958,0.624958,73688.0,73688.0
1,27,62422,-1.326817,-0.065301,-1.320166,27.0,27.0,62422.0,0.181818,0.461501,0.461501,62422.0,62422.0
2,33,61521,-0.661746,-0.110592,-0.658429,33.0,33.0,61521.0,0.363636,0.448428,0.448428,61521.0,61521.0
3,35,61619,-0.440055,-0.105666,-0.437850,35.0,35.0,61619.0,0.424242,0.449850,0.449850,61619.0,61619.0
4,43,71805,0.446706,0.406351,0.444467,43.0,43.0,71805.0,0.666667,0.597638,0.597638,71805.0,71805.0

In [54]:
df[['age_inverse_scaler','salary_inverse_scaler']] = scaler.inverse_transform(df[['age_mimx','salary_mimx']])

In [55]:
df.head()

,age,salary,age_scaled,salary_scaled,age_scaled_manual,age_inverse_manual,age_inverse,salary_inverse,age_mimx,salary_mimx,salary_mimx_manual,age_inverse_mimx,salary_inverse_mimx,age_inverse_scaler,salary_inverse_scaler
0,32,73688,-0.772591,0.501003,-0.768718,32.0,32.0,73688.0,0.333333,0.624958,0.624958,73688.0,73688.0,32.0,73688.0
1,27,62422,-1.326817,-0.065301,-1.320166,27.0,27.0,62422.0,0.181818,0.461501,0.461501,62422.0,62422.0,27.0,62422.0
2,33,61521,-0.661746,-0.110592,-0.658429,33.0,33.0,61521.0,0.363636,0.448428,0.448428,61521.0,61521.0,33.0,61521.0
3,35,61619,-0.440055,-0.105666,-0.437850,35.0,35.0,61619.0,0.424242,0.449850,0.449850,61619.0,61619.0,35.0,61619.0
4,43,71805,0.446706,0.406351,0.444467,43.0,43.0,71805.0,0.666667,0.597638,0.597638,71805.0,71805.0,43.0,71805.0