In [2]:
from sklearn.datasets import fetch_california_housing

housing = fetch_california_housing()

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.DataFrame(housing.data,columns=housing.feature_names)

In [7]:
df["Target"] = housing.target

In [10]:
X = df.drop('Target',axis=1)

In [20]:
X

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

In [12]:
y = df['Target']

In [13]:
y

0        4.526
1        3.585
2        3.521
3        3.413
4        3.422
         ...
20635    0.781
20636    0.771
20637    0.923
20638    0.847
20639    0.894
Name: Target, Length: 20640, dtype: float64

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [17]:
from sklearn.linear_model import LinearRegression

linear = LinearRegression()

model = linear.fit(X_train,y_train)

In [18]:
model.intercept_

np.float64(-37.02327770606413)

In [19]:
model.coef_

array([ 4.48674910e-01,  9.72425752e-03, -1.23323343e-01,  7.83144907e-01,
       -2.02962058e-06, -3.52631849e-03, -4.19792487e-01, -4.33708065e-01])

In [23]:
y_test

20046    0.47700
3024     0.45800
15663    5.00001
20484    2.18600
9814     2.78000
          ...
15362    2.63300
16623    2.66800
18086    5.00001
2144     0.72300
3665     1.51500
Name: Target, Length: 4128, dtype: float64

In [24]:
X_test

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
20046,1.6812,25.0,4.192201,1.022284,1392.0,3.877437,36.06,-119.01
3024,2.5313,30.0,5.039384,1.193493,1565.0,2.679795,35.14,-119.46
15663,3.4801,52.0,3.977155,1.185877,1310.0,1.360332,37.80,-122.44
20484,5.7376,17.0,6.163636,1.020202,1705.0,3.444444,34.28,-118.72
9814,3.7250,34.0,5.492991,1.028037,1063.0,2.483645,36.62,-121.93
...,...,...,...,...,...,...,...,...
15362,4.6050,16.0,7.002212,1.066372,1351.0,2.988938,33.36,-117.22
16623,2.7266,28.0,6.131915,1.256738,1650.0,2.340426,35.36,-120.83
18086,9.2298,25.0,7.237676,0.947183,1585.0,2.790493,37.31,-122.05
2144,2.7850,36.0,5.289030,0.983122,1227.0,2.588608,36.77,-119.76
3665,3.5521,17.0,3.988839,1.033482,1671.0,3.729911,34.22,-118.37

In [25]:
model.predict([[1.6812,25.0,4.192201,1.022284,1392.0,3.877437,36.06,-119.01]])

/opt/homebrew/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([0.71912269])

In [21]:
y_pred = model.predict(X_test)

In [26]:
y_pred

array([0.71912284, 1.76401657, 2.70965883, ..., 4.46877017, 1.18751119,
       2.00940251], shape=(4128,))

In [22]:
from sklearn.metrics import r2_score

print(r2_score(y_test,y_pred))

0.5757877060324508

In [27]:
data = {
    'Experience':[1,2,4,6,8],
    'Skills':[2,3,5,7,8],
    'Education':[1,2,3,3,4],
    'Salary':[30000,40000,65000,90000,120000]
}

df = pd.DataFrame(data)
print(df)

   Experience  Skills  Education  Salary
0           1       2          1   30000
1           2       3          2   40000
2           4       5          3   65000
3           6       7          3   90000
4           8       8          4  120000

In [28]:
X = df[['Experience','Skills','Education']]
y = df["Salary"]

In [29]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [30]:
linear = LinearRegression()

model = linear.fit(X_train,y_train)

y_pred = model.predict(X_test)

In [32]:
y_test

1    40000
Name: Salary, dtype: int64

In [31]:
y_pred

array([41250.])

In [33]:
model.intercept_

np.float64(25000.000000000007)

In [34]:
model.coef_

array([18750., -6250., -1250.])

In [36]:
model.predict([[2,3,4]])

/opt/homebrew/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([38750.])